import React from "react";
import type {Metadata} from "next";
import {GlobalProvider} from "@/app/GlobalProvider";
import "primeicons/primeicons.css";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <head>
            <link id="theme-link" rel="stylesheet" href={`/themes/mdc-dark-indigo/theme.css`}/>
        </head>
        <body>
        <GlobalProvider>
            {children}
        </GlobalProvider>
        </body>
        </html>
    );
}
